/home/human/Projects/adt-framework/_cortex/ops/dttp*.log
/home/human/Projects/adt-framework/_cortex/ops/dtcp*.log
/home/human/Projects/adt-framework/_cortex/ops/adt_center.log
{
    daily
    missingok
    rotate 7
    compress
    delaycompress
    notifempty
    create 664 dttp dttp
}
